import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Nav } from "./components/navbar-menu";
import { ThemeProvider } from "@/components/theme-provider";
import { ModeToggle } from "./components/toggle-mode";
import Footer from "./components/footer";
import ToastProvider from "./providers/toast.provider";
import AppProvider from "./app-provider";
import { cookies } from "next/headers";
const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});
const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = cookies();
  const sessionToken = cookieStore.get("sessionToken");
  const refreshToken = cookieStore.get("refreshToken");
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <ToastProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <AppProvider
              inititalRefreshToken={refreshToken?.value}
              inititalSessionToken={sessionToken?.value}
            >
              {children}
            </AppProvider>
            <ModeToggle />
          </ThemeProvider>
        </ToastProvider>
      </body>
    </html>
  );
}
