import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Nav } from "./components/navbar-menu";
import { ThemeProvider } from "@/components/theme-provider";
import { ModeToggle } from "./components/toggle-mode";
import { Toaster } from "@/components/ui/toaster";
import Footer from "./components/footer";
import AppProvider from "./app-provider";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});
const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          "min-h-screen bg-slate-100 font-sans antialiased",
          fontSans.variable
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <AppProvider>
            <Nav />
            {children}
            <Footer />
          </AppProvider>
          <Toaster />
          <ModeToggle />
        </ThemeProvider>
      </body>
    </html>
  );
}
