Resources:
  User:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: User
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: email
          AttributeType: S
        - AttributeName: phone
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: EmailIndex
          KeySchema:
            - AttributeName: email
              KeyType: HASH
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
        - IndexName: PhoneIndex
          KeySchema:
            - AttributeName: phone
              KeyType: HASH
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1

  Blog:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Blog
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      AttributeDefinitions:
        - AttributeName: blogId
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: blogId
          KeyType: HASH
        - AttributeName: userId
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: UserIndex
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1

  RefreshToken:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: RefreshToken
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      AttributeDefinitions:
        - AttributeName: tokenId
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
        - AttributeName: token
          AttributeType: S
      KeySchema:
        - AttributeName: tokenId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: TokenIndex
          KeySchema:
            - AttributeName: token
              KeyType: HASH
            - AttributeName: userId
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1

  Hashtag:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Hashtag
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      AttributeDefinitions:
        - AttributeName: hashtagId
          AttributeType: S
        - AttributeName: content
          AttributeType: S
      KeySchema:
        - AttributeName: hashtagId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: ContentIndex
          KeySchema:
            - AttributeName: content
              KeyType: HASH
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1

  BlogHashtag:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: BlogHashtag
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      AttributeDefinitions:
        - AttributeName: blogId
          AttributeType: S
        - AttributeName: hashtagId
          AttributeType: S
      KeySchema:
        - AttributeName: blogId
          KeyType: HASH
        - AttributeName: hashtagId
          KeyType: RANGE

  Like:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Like
      AttributeDefinitions:
        - AttributeName: likeId
          AttributeType: S
        - AttributeName: blogId
          AttributeType: S
      KeySchema:
        - AttributeName: likeId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: BlogIndex
          KeySchema:
            - AttributeName: blogId
              KeyType: HASH
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
