import { attribute, autoGeneratedHashKey, table } from '@aws/dynamodb-data-mapper-annotations';
import { v4 } from "uuid";
import { DynamoDB } from "aws-sdk";

const dateMarshall = (value: Date): DynamoDB.AttributeValue =>
  ({ I: value.getTime() } as DynamoDB.AttributeValue);
const dateUnmarshall = ({ N }: DynamoDB.AttributeValue): Date | undefined =>
    N ? new Date(N) : undefined;
  
@table('Base')
export class BaseModel {
    @autoGeneratedHashKey()
    id?: string = v4();

    @attribute({ marshall: dateMarshall, unmarshall: dateUnmarshall })
    created_at?: Date;
  
    @attribute({ marshall: dateMarshall, unmarshall: dateUnmarshall })
    updated_at?: Date;

    @attribute()
    deleted?: boolean;
}