import { attribute, autoGeneratedHashKey, table } from '@aws/dynamodb-data-mapper-annotations';

import { ISOdateType } from './date-dynamo';

@table('Blog')
export class Blog {
	@autoGeneratedHashKey()
	blogId!: string;

	@attribute()
	userId?: string;

	@attribute()
	title?: string;

	@attribute()
	content?: string;

	@attribute({ ...ISOdateType, defaultProvider: () => new Date() })
	created_at?: Date;

	@attribute({ ...ISOdateType, defaultProvider: () => new Date() })
	updated_at?: Date;

	@attribute()
	deleted?: boolean;

	@attribute()
	image?: string;
}
