import { attribute, autoGeneratedHashKey, table } from '@aws/dynamodb-data-mapper-annotations';

@table('BlogHashtag')
export class BlogHashtag {
	@autoGeneratedHashKey()
	blogHashtagId?: string;

	@attribute()
	blogId!: string;

	@attribute()
	hashtagId!: string;
}
