// import {
//     attribute,
//     autoGeneratedHashKey,
//     rangeKey,
//     table,
// } from '@aws/dynamodb-data-mapper-annotations';

// @table('blogs')
// class Blog {
//     @autoGeneratedHashKey()
//     id: string;
    
//     @rangeKey()
//     createdAt: Date;
    
//     @attribute()
//     authorUsername: string;
    
//     @attribute()
//     title: string;
// }