import { attribute, autoGeneratedHashKey, table } from '@aws/dynamodb-data-mapper-annotations';

import { ISOdateType } from './date-dynamo';

@table('Hashtag')
export class Hashtag {
	@autoGeneratedHashKey()
	hashtagId?: string;

	@attribute()
	content!: string;

	@attribute({ ...ISOdateType, defaultProvider: () => new Date() })
	created_at?: Date;

	@attribute({ ...ISOdateType, defaultProvider: () => new Date() })
	updated_at?: Date;

	@attribute()
	deleted?: boolean;
}
