import { attribute, autoGeneratedHashKey, table } from '@aws/dynamodb-data-mapper-annotations';

import { dateMarshall, dateUnmarshall } from './date-dynamo';

@table('Hashtag')
export class Hashtag {
	@autoGeneratedHashKey()
	hashtagId?: string;

	@attribute()
	content!: string;

	@attribute({ marshall: dateMarshall, unmarshall: dateUnmarshall })
	created_at?: string;

	@attribute({ marshall: dateMarshall, unmarshall: dateUnmarshall })
	updated_at?: string;

	@attribute()
	deleted?: boolean;
}
