import {
  attribute,
  autoGeneratedHashKey,
  table
} from "@aws/dynamodb-data-mapper-annotations";
import { dateMarshall, dateUnmarshall } from "./date-dynamo";


@table("Hashtag")
export class Hashtag {
  @autoGeneratedHashKey()
  hashtagId?: string;

  @attribute()
  name?: string;

  @attribute({ marshall: dateMarshall, unmarshall: dateUnmarshall })
  created_at?: Date;
  
  @attribute({ marshall: dateMarshall, unmarshall: dateUnmarshall })
  updated_at?: Date;
  
  @attribute()
  deleted?: boolean;
}