import { attribute, autoGeneratedHashKey, table } from '@aws/dynamodb-data-mapper-annotations';

import { ISOdateType } from './date-dynamo';

// Import the Blog model

@table('RefreshToken')
export class RefreshToken {
	@autoGeneratedHashKey()
	tokenId?: string;

	@attribute()
	userId!: string;

	@attribute()
	token!: string;

	@attribute({ ...ISOdateType, defaultProvider: () => new Date() })
	created_at?: Date;

	@attribute({ ...ISOdateType, defaultProvider: () => new Date() })
	updated_at?: Date;

	@attribute()
	deleted?: boolean;
}
