import { attribute, autoGeneratedHashKey, table } from '@aws/dynamodb-data-mapper-annotations';

import { Blog } from './blog-schema';
import { dateMarshall, dateUnmarshall } from './date-dynamo';

// Import the Blog model

@table('Token')
export class Token {
	@autoGeneratedHashKey()
	tokenId?: string;

	@attribute()
	@attribute({
		defaultProvider: () => new Date(),
		marshall: dateMarshall,
		unmarshall: dateUnmarshall
	})
	createdAt?: Date;

	@attribute({
		defaultProvider: () => new Date(),
		marshall: dateMarshall,
		unmarshall: dateUnmarshall
	})
	updatedAt?: Date;

	@attribute()
	deleted?: boolean;
}
