import {
  attribute,
  autoGeneratedHashKey,
  table
} from "@aws/dynamodb-data-mapper-annotations";
import { dateMarshall, dateUnmarshall } from "./date-dynamo";
import { Blog } from './blog-schema'; // Import the Blog model

@table("User")
export class User {
    @autoGeneratedHashKey()
    userId?: string;

    @attribute()
    firstName?: string;

    @attribute()
    lastName?: string;

    @attribute()
    email?: string;

    @attribute()
    phone?: string;

    @attribute()
    role?: string;

    @attribute()
    blogs?: Blog[];

    @attribute({ marshall: dateMarshall, unmarshall: dateUnmarshall })
    created_at?: Date;
  
    @attribute({ marshall: dateMarshall, unmarshall: dateUnmarshall })
    updated_at?: Date;

    @attribute()
    deleted?: boolean;
}