import { attribute, autoGeneratedHashKey, table } from '@aws/dynamodb-data-mapper-annotations';

import { Blog } from './blog-schema';
import { ISOdateType } from './date-dynamo';

@table('User')
export class User {
	@autoGeneratedHashKey()
	userId!: string;

	@attribute()
	firstName?: string;

	@attribute()
	lastName?: string;

	@attribute()
	email?: string;

	@attribute()
	phone?: string;

	@attribute()
	role?: string;

	@attribute()
	blogs?: Blog[];

	@attribute()
	password?: string;

	@attribute({ ...ISOdateType, defaultProvider: () => new Date() })
	created_at?: Date;

	@attribute({ ...ISOdateType, defaultProvider: () => new Date() })
	updated_at?: Date;

	@attribute()
	deleted?: boolean;
}
